"""Structural guardrail: Claude and Cursor slash-command surfaces (#227).

# @layer: unit
# @spec: 227-command-surface-parity
# @regression

Context: Claude Code loads ``.claude/commands/**``; Cursor loads
``.cursor/commands/*.md`` ONLY — it never scans ``.claude/commands/``. Four
hand-written commands (``/fix-bug``, ``/implement-feature``, ``/maintainer``,
``/triage-issue``) used to live only on the Claude side, so the delivery
flow was not executable from Cursor and parity was hand-maintained and
silently drifted.

The fix pins three mechanisms so the two surfaces cannot drift apart again:

* ``scripts/sync-cursor-commands.sh`` generates thin Cursor wrappers for a
  declared list of top-level ``.claude/commands/<name>.md`` commands.
* ``scripts/sync-awos-cursor-commands.sh`` (pre-existing, unchanged by
  #227) already generates ``.cursor/commands/awos-<name>.md`` from
  ``.awos/commands/<name>.md``.
* ``/maintainer`` and ``/triage-issue`` were removed from
  ``.claude/commands/`` outright rather than mirrored (see
  ``context/spec/227-command-surface-parity/flow-log.md``).

These tests are STRUCTURAL ONLY — file-level assertions against the repo
tree. They never invoke ``claude``, ``cursor-agent``, or any agent, and
never shell out to a network.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CLAUDE_CMDS = REPO_ROOT / ".claude" / "commands"
CLAUDE_AWOS_CMDS = CLAUDE_CMDS / "awos"
CURSOR_CMDS = REPO_ROOT / ".cursor" / "commands"
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync-cursor-commands.sh"

# The generated-file marker the sync-cursor-commands.sh wrappers carry so
# nobody hand-edits one into silent drift.
GENERATOR_MARKER_SCRIPT = "scripts/sync-cursor-commands.sh"

# ─── Allowlists (dicts, not bare sets, so every entry must be justified) ──

# Top-level/AWOS Claude commands with no Cursor counterpart. Empty today —
# if you add an entry, you must also add a non-empty reason.
CLAUDE_ONLY: dict[str, str] = {}

# Cursor commands with no direct Claude-source counterpart.
CURSOR_ONLY: dict[str, str] = {
    "awos-flow": (
        "provided to Claude by the awos@awos-marketplace plugin; the "
        "committed .cursor/commands/awos-flow.md is the Layer C artifact "
        "generated by scripts/sync-awos-plugin-cursor.sh because Cursor "
        "has no plugin runtime"
    ),
}

# Cursor wrappers that are deliberately hand-written rather than produced
# by scripts/sync-cursor-commands.sh.
HAND_WRITTEN_CURSOR_WRAPPERS: dict[str, str] = {
    "release": (
        "kept as a byte-identical hand copy of .claude/commands/release.md; "
        "it independently loads the shared .claude/skills/release/SKILL.md "
        "(Cursor reads .claude/skills/ natively), so it is not produced by "
        "scripts/sync-cursor-commands.sh and carries no generator marker"
    ),
}

# Removed in #227 — must never come back, and no live doc may reference
# them as if they were still invocable.
REMOVED_COMMAND_NAMES = ("maintainer", "triage-issue")
# Negative lookbehind on the leading slash keeps this from tripping on an
# unrelated filesystem path like "docs/tests/maintainer reference" — a real
# slash-command mention is never itself preceded by another path segment.
REMOVED_COMMAND_PATTERNS = [re.compile(rf"(?<![\w/])/{name}\b") for name in REMOVED_COMMAND_NAMES]

# A small, explicit set of live, currently-accurate docs to scan for
# lingering references to the removed commands. Deliberately excludes:
#   - demo/**                          (synthetic vault fixtures, not repo docs)
#   - context/spec/**                  (historical flow logs / specs for past work)
#   - CHANGELOG.md                     (historical record of already-released versions)
#   - docs/maintainers/DECLINED.md     (deliberately preserves the original wording
#                                        plus a dated retirement note)
LIVE_DOCS = [
    REPO_ROOT / "docs" / "maintainers" / "README.md",
    REPO_ROOT / "docs" / "maintainers" / "TRIAGE.md",
    REPO_ROOT / "docs" / "maintainers" / "AWOS-CURSOR.md",
    REPO_ROOT / "docs" / "reference" / "slash-commands.md",
    REPO_ROOT / "docs" / "reference" / "cli.md",
    REPO_ROOT / "CONTRIBUTING.md",
    REPO_ROOT / "CLAUDE.md",
    REPO_ROOT / "context" / "product" / "delivery-flow.md",
]


# ─── Helpers ──────────────────────────────────────────────────────────────


def _top_level_claude_commands() -> list[Path]:
    return sorted(p for p in CLAUDE_CMDS.glob("*.md") if p.stem != "README")


def _awos_claude_commands() -> list[Path]:
    return sorted(p for p in CLAUDE_AWOS_CMDS.glob("*.md") if p.stem != "README")


def _cursor_commands() -> list[Path]:
    return sorted(p for p in CURSOR_CMDS.glob("*.md") if p.stem != "README")


def _claude_source_for_cursor(stem: str) -> Path:
    """The Claude-side source of truth a Cursor command stem should map to."""
    if stem.startswith("awos-"):
        return CLAUDE_AWOS_CMDS / f"{stem[len('awos-'):]}.md"
    return CLAUDE_CMDS / f"{stem}.md"


def _expected_source_path_str(cursor_stem: str) -> str:
    """The literal POSIX path a pointer wrapper must name (shape b)."""
    if cursor_stem.startswith("awos-"):
        name = cursor_stem[len("awos-") :]
        return f".awos/commands/{name}.md"
    return f".claude/commands/{cursor_stem}.md"


def _declared_sync_commands() -> list[str]:
    """Parse the COMMANDS=(...) bash array out of sync-cursor-commands.sh."""
    text = SYNC_SCRIPT.read_text(encoding="utf-8")
    m = re.search(r"COMMANDS=\(\s*(.*?)\)", text, re.S)
    assert m, f"couldn't find COMMANDS=(...) array in {SYNC_SCRIPT.relative_to(REPO_ROOT)}"
    names: list[str] = []
    for line in m.group(1).splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            names.append(line)
    return names


# ─── Allowlist hygiene ──────────────────────────────────────────────────


def test_claude_only_allowlist_entries_carry_a_reason():
    # @regression
    for name, reason in CLAUDE_ONLY.items():
        assert reason.strip(), f"CLAUDE_ONLY[{name!r}] must carry a non-empty reason"


def test_cursor_only_allowlist_entries_carry_a_reason():
    # @regression
    for name, reason in CURSOR_ONLY.items():
        assert reason.strip(), f"CURSOR_ONLY[{name!r}] must carry a non-empty reason"


def test_cursor_only_awos_flow_reason_names_the_plugin():
    # @regression
    reason = CURSOR_ONLY.get("awos-flow", "")
    assert "plugin" in reason.lower(), (
        f"CURSOR_ONLY['awos-flow'] reason must explain it is plugin-provided, got: {reason!r}"
    )


def test_hand_written_cursor_wrapper_allowlist_entries_carry_a_reason():
    # @regression
    for name, reason in HAND_WRITTEN_CURSOR_WRAPPERS.items():
        assert reason.strip(), f"HAND_WRITTEN_CURSOR_WRAPPERS[{name!r}] must carry a non-empty reason"
        p = CURSOR_CMDS / f"{name}.md"
        assert p.is_file(), (
            f"allowlisted hand-written wrapper {p.relative_to(REPO_ROOT)} does not exist"
        )


# ─── Property 1: forward mapping (Claude -> Cursor) ────────────────────


def test_every_claude_top_level_command_has_a_cursor_counterpart():
    # @regression
    offenders: list[str] = []
    for p in _top_level_claude_commands():
        if p.stem in CLAUDE_ONLY:
            continue
        out = CURSOR_CMDS / f"{p.stem}.md"
        if not out.is_file():
            offenders.append(
                f"{p.relative_to(REPO_ROOT)}: no {out.relative_to(REPO_ROOT)} wrapper"
            )
    assert not offenders, "Claude→Cursor parity gap (top level):\n  " + "\n  ".join(offenders)


def test_every_claude_awos_command_has_a_cursor_counterpart():
    # @regression
    offenders: list[str] = []
    for p in _awos_claude_commands():
        if p.stem in CLAUDE_ONLY:
            continue
        out = CURSOR_CMDS / f"awos-{p.stem}.md"
        if not out.is_file():
            offenders.append(
                f"{p.relative_to(REPO_ROOT)}: no {out.relative_to(REPO_ROOT)} wrapper"
            )
    assert not offenders, "Claude→Cursor parity gap (awos):\n  " + "\n  ".join(offenders)


# ─── Property 2: reverse mapping (Cursor -> Claude) ────────────────────


def test_every_cursor_command_maps_back_to_a_claude_source():
    # @regression
    offenders: list[str] = []
    for p in _cursor_commands():
        if p.stem in CURSOR_ONLY:
            continue
        src = _claude_source_for_cursor(p.stem)
        if not src.is_file():
            offenders.append(
                f"{p.relative_to(REPO_ROOT)}: no Claude counterpart at {src.relative_to(REPO_ROOT)}"
            )
    assert not offenders, "Cursor→Claude parity gap:\n  " + "\n  ".join(offenders)


# ─── Property 3: legal wrapper shapes ───────────────────────────────────


def test_cursor_wrappers_are_byte_identical_or_point_at_their_source():
    # @regression
    offenders: list[str] = []
    for p in _cursor_commands():
        if p.stem in CURSOR_ONLY:
            continue
        src = _claude_source_for_cursor(p.stem)
        if not src.is_file():
            continue  # already reported by the reverse-mapping test
        cursor_text = p.read_text(encoding="utf-8")
        claude_text = src.read_text(encoding="utf-8")
        if cursor_text == claude_text:
            continue  # shape (a): byte-identical
        expected_path = _expected_source_path_str(p.stem)
        if expected_path in cursor_text:
            continue  # shape (b): pointer names its source of truth
        offenders.append(
            f"{p.relative_to(REPO_ROOT)}: neither byte-identical to "
            f"{src.relative_to(REPO_ROOT)} (shape a) nor containing the literal "
            f"path {expected_path!r} (shape b)"
        )
    assert not offenders, "illegal Cursor wrapper shape:\n  " + "\n  ".join(offenders)


# ─── Property 4: generator declaration honesty ─────────────────────────


def test_sync_cursor_commands_array_matches_reality():
    # @regression
    offenders: list[str] = []
    for name in _declared_sync_commands():
        src = CLAUDE_CMDS / f"{name}.md"
        out = CURSOR_CMDS / f"{name}.md"
        if not src.is_file():
            offenders.append(
                f"COMMANDS declares {name!r} but {src.relative_to(REPO_ROOT)} does not exist"
            )
        if not out.is_file():
            offenders.append(
                f"COMMANDS declares {name!r} but {out.relative_to(REPO_ROOT)} was not generated"
            )
    assert not offenders, (
        "scripts/sync-cursor-commands.sh COMMANDS array drift:\n  " + "\n  ".join(offenders)
    )


# ─── Property 5: generated files are marked ────────────────────────────


def test_generated_cursor_wrappers_carry_their_generator_marker():
    # @regression
    # Scope: scripts/sync-cursor-commands.sh is the generator #227 adds, for
    # the top-level (non-awos-prefixed) Cursor commands. The pre-existing
    # awos-* pipeline (scripts/sync-awos-cursor-commands.sh /
    # scripts/sync-awos-plugin-cursor.sh) predates #227, uses its own marker
    # convention, and is out of scope here (see
    # context/spec/227-command-surface-parity/flow-log.md, "diagnose" #3).
    offenders: list[str] = []
    for p in _cursor_commands():
        if p.stem in CURSOR_ONLY or p.stem in HAND_WRITTEN_CURSOR_WRAPPERS:
            continue
        if p.stem.startswith("awos-"):
            continue
        text = p.read_text(encoding="utf-8")
        if GENERATOR_MARKER_SCRIPT not in text:
            offenders.append(
                f"{p.relative_to(REPO_ROOT)}: missing generated-file marker naming "
                f"{GENERATOR_MARKER_SCRIPT}"
            )
    assert not offenders, "unmarked generated Cursor wrapper:\n  " + "\n  ".join(offenders)


# ─── Property 6: removed commands stay removed ─────────────────────────


def test_removed_commands_do_not_exist_on_claude_side():
    # @regression
    offenders = [
        name for name in REMOVED_COMMAND_NAMES if (CLAUDE_CMDS / f"{name}.md").is_file()
    ]
    assert not offenders, (
        "removed command(s) reappeared under .claude/commands/: " + ", ".join(offenders)
    )


def test_removed_commands_do_not_exist_on_cursor_side():
    # @regression
    offenders = [
        name for name in REMOVED_COMMAND_NAMES if (CURSOR_CMDS / f"{name}.md").is_file()
    ]
    assert not offenders, (
        "removed command(s) reappeared under .cursor/commands/: " + ", ".join(offenders)
    )


def test_removed_commands_unreferenced_as_invocable_in_live_docs():
    # @regression
    offenders: list[str] = []
    for doc in LIVE_DOCS:
        if not doc.is_file():
            continue
        text = doc.read_text(encoding="utf-8")
        for pattern in REMOVED_COMMAND_PATTERNS:
            if pattern.search(text):
                offenders.append(f"{doc.relative_to(REPO_ROOT)}: still references {pattern.pattern!r}")
    assert not offenders, (
        "removed command referenced as if still invocable:\n  " + "\n  ".join(offenders)
    )
