#!/usr/bin/env bash
# Regenerate Cursor wrappers for hand-written top-level Claude commands.
#
# Why: Cursor Agent resolves slash commands from `.cursor/commands/*.md` only —
# it never scans `.claude/commands/`. A command that lives solely under
# `.claude/commands/` is therefore Claude-only. This script emits a thin
# `.cursor/commands/<name>.md` wrapper that points Cursor at the Claude file as
# the single source of truth, so the two surfaces cannot drift apart.
#
# `.cursor/commands/release.md` is deliberately NOT generated: it loads the
# shared `.claude/skills/release/SKILL.md` (which Cursor reads natively) rather
# than mirroring a Claude command, so it stays hand-written.
#
# Run after editing any command listed in COMMANDS below:
#   ./scripts/sync-cursor-commands.sh
#
# Safe to re-run; overwrites generated wrappers only.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/.claude/commands"
DST="$ROOT/.cursor/commands"

# Top-level `.claude/commands/<name>.md` commands that need a Cursor wrapper.
COMMANDS=(
  fix-bug
  implement-feature
)

mkdir -p "$DST"

written=0
for name in "${COMMANDS[@]}"; do
  src="$SRC/${name}.md"
  out="$DST/${name}.md"

  if [[ ! -f "$src" ]]; then
    echo "error: missing $src — cannot generate .cursor/commands/${name}.md" >&2
    exit 1
  fi

  # Prefer description from the Claude command frontmatter.
  desc="$(
    python3 - "$src" <<'PY'
import re, sys
from pathlib import Path
text = Path(sys.argv[1]).read_text(encoding="utf-8")
m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
if not m:
    print(f"Claude command: {Path(sys.argv[1]).stem}")
    raise SystemExit(0)
block = m.group(1)
dm = re.search(r'^description:\s*(.+)$', block, re.M)
if not dm:
    print(f"Claude command: {Path(sys.argv[1]).stem}")
    raise SystemExit(0)
val = dm.group(1).strip()
if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
    val = val[1:-1]
print(val)
PY
  )"

  cat >"$out" <<EOF
---
description: ${desc}
---

<!-- Generated by scripts/sync-cursor-commands.sh — do not edit by hand; edit .claude/commands/${name}.md and re-run the script. -->

# /${name} (Cursor)

Follow \`.claude/commands/${name}.md\` as the source of truth and execute it end to end — every stage, gate, and check in that file applies here unchanged.

Apply the tool mapping in \`.cursor/rules/awos-cursor-runtime.mdc\`.

**Multiple-choice interaction (strict):** when the command prompt says \`AskUserQuestion\`, call native \`AskQuestion\` if it is already listed as a first-class tool this turn (invoke by name). Do **not** \`CallDynamicTool\` with \`namespace: cursor\` and \`toolName: AskQuestion\` — that tool is not in the cursor namespace. Use prose numbered choices **only** if native \`AskQuestion\` is missing. Never call \`AskUserQuestion\` (Claude-only name).

Optional user hint (if provided after the slash command): treat it as \`\$ARGUMENTS\` / the \`<user_prompt>\` in that command file.
EOF

  echo "wrote .cursor/commands/${name}.md  →  /${name}"
  written=$((written + 1))
done

echo "synced ${written} Cursor command wrapper(s) from .claude/commands/"
echo "Tip: reload the Cursor window if the slash menu is stale."
