#!/usr/bin/env bash
# Regenerate Cursor wrappers for hand-written top-level Claude commands.
#
# Why: Cursor Agent resolves slash commands from `.cursor/commands/*.md` only —
# it never scans `.claude/commands/`. A command that lives solely under
# `.claude/commands/` is therefore Claude-only. This script emits a thin
# `.cursor/commands/<name>.md` wrapper that points Cursor at the Claude file as
# the single source of truth, so the two surfaces cannot drift apart.
#
# `.cursor/commands/release.md` is deliberately NOT generated: it loads the
# shared `.claude/skills/release/SKILL.md` (which Cursor reads natively) rather
# than mirroring a Claude command, so it stays hand-written.
#
# Run after editing any command listed in COMMANDS below:
#   ./scripts/sync-cursor-commands.sh
#
# Safe to re-run; overwrites generated wrappers only. Wrappers carrying this
# script's generator marker whose name is no longer in COMMANDS are pruned;
# files without the marker (hand-written `release.md`, the `awos-*` family) are
# never touched.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/.claude/commands"
DST="$ROOT/.cursor/commands"

# Marker embedded in every wrapper this script writes; the prune pass below
# matches on it so hand-written wrappers stay put.
MARKER="scripts/sync-cursor-commands.sh"

# Top-level `.claude/commands/<name>.md` commands that need a Cursor wrapper.
COMMANDS=(
  fix-bug
  implement-feature
)

mkdir -p "$DST"

written=0
for name in "${COMMANDS[@]}"; do
  src="$SRC/${name}.md"
  out="$DST/${name}.md"

  if [[ ! -f "$src" ]]; then
    echo "error: missing $src — cannot generate .cursor/commands/${name}.md" >&2
    exit 1
  fi

  # Prefer description from the Claude command frontmatter. Always emitted as a
  # JSON-quoted (hence valid YAML double-quoted) scalar so a value containing
  # `: ` or opening with an indicator character cannot corrupt the frontmatter.
  desc="$(
    python3 - "$src" <<'PY'
import json, re, sys
from pathlib import Path
path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
if not m:
    print(json.dumps(f"Claude command: {path.stem}", ensure_ascii=False))
    raise SystemExit(0)
block = m.group(1)
dm = re.search(r'^description:\s*(.+)$', block, re.M)
if not dm:
    print(json.dumps(f"Claude command: {path.stem}", ensure_ascii=False))
    raise SystemExit(0)
val = dm.group(1).strip()
if val in (">", "|", ">-", "|-", ">+", "|+"):
    print(
        f"error: {path} uses a YAML block scalar for `description:` — "
        "put the description on one line so it can be copied into the wrapper",
        file=sys.stderr,
    )
    raise SystemExit(1)
print(json.dumps(val, ensure_ascii=False))
PY
  )"

  cat >"$out" <<EOF
---
description: ${desc}
---

<!-- Generated by scripts/sync-cursor-commands.sh — do not edit by hand; edit .claude/commands/${name}.md and re-run the script. -->

# /${name} (Cursor)

Read \`.claude/commands/${name}.md\` in full before doing anything else, then execute it end to end — every stage, gate, and check in that file applies here unchanged.

Apply the tool mapping in \`.cursor/rules/awos-cursor-runtime.mdc\`.

**Multiple-choice interaction (strict):** when the command prompt says \`AskUserQuestion\`, call native \`AskQuestion\` if it is already listed as a first-class tool this turn (invoke by name). Do **not** \`CallDynamicTool\` with \`namespace: cursor\` and \`toolName: AskQuestion\` — that tool is not in the cursor namespace. Use prose numbered choices **only** if native \`AskQuestion\` is missing. Never call \`AskUserQuestion\` (Claude-only name).

Optional user hint (if provided after the slash command): treat it as \`\$ARGUMENTS\` / the \`<user_prompt>\` in that command file.
EOF

  echo "wrote .cursor/commands/${name}.md  →  /${name}"
  written=$((written + 1))
done

# Prune wrappers this script generated for names since dropped from COMMANDS.
pruned=0
shopt -s nullglob
for stale in "$DST"/*.md; do
  name="$(basename "$stale" .md)"
  grep -qF "$MARKER" "$stale" || continue
  declared=0
  for cmd in "${COMMANDS[@]}"; do
    if [[ "$name" == "$cmd" ]]; then
      declared=1
      break
    fi
  done
  if [[ "$declared" -eq 0 ]]; then
    rm -f "$stale"
    echo "pruned .cursor/commands/${name}.md  (no longer in COMMANDS)"
    pruned=$((pruned + 1))
  fi
done

echo "synced ${written} Cursor command wrapper(s) from .claude/commands/, pruned ${pruned}"
echo "Tip: reload the Cursor window if the slash menu is stale."
